import { PageName } from './PageNames';

export const STATIC_TEXT = {
  [PageName.Profile]: {
    guidesTab: 'Guides reward',
    refferalTab: 'Referral reward',
    settingsTab: 'Account settings',
    walletTab: 'Wallet',
  },
  [PageName.ProfileSettings]: {
    userNameTitle: 'User name',
    socialTitle: 'Уour social account',
    connectMail: 'Connect Email Address',
    connectTwitter: 'Connect Twitter Account',
    setPass: 'Set password',
    logout: 'Log out',
    editMailTitle: 'Enter email address',
    editNameTitle: 'Name editing',
    setPassTitle: 'Set password',
    changePassTitle: 'Change password',
    fieldName: 'Enter your name',
    fieldMail: 'Enter email address',
    fieldPass: 'Enter password',
    fieldEnterPass: 'Enter password',
    fieldRepeatPass: 'Repeat password',
    fieldLastPass: 'Enter last password',
    fieldNewPass: 'Enter new password',
    connectSocial: 'Connect with social account',
    socialGoogle: 'Google',
    btnSave: 'Save',
  },
  [PageName.GuidesGallery]: {
    subtitle:
      "Do you know what an exchange is? Don't worry, this is not a test and it g won't affect any result Don't dfhhhdfj Don't worry",
    buttonText: "Let's go!",
    guideStatus: {
      inProgress: 'in progress',
      completed: 'completed',
      new: 'new',
    },
    guideLevel: { beginner: 'beginner', medium: 'medium', advanced: 'advanced' },
    guideTime: 'min',
    guideRewardTitle: 'Reward',
    guideRewardCount: 'left',
  },
  [PageName.ProfileWallet]: {
    formTitle: 'Your wallet address',
    statusWallet: 'Connected',
    balanceTitle: 'Balance ETH',
    balanceValue: '0',
    networkTitle: 'Connected network',
    networkName: 'Ethereum',
    statusForm: 'Disconnect',
  },
};
