import { PageName } from './PageNames';

export const TEXT_KEYS = {
  METAMASK_CONNECT: [
    `${PageName.Metamask}_NoWallet.statusText`,
    `${PageName.Metamask}_NoWallet.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_NoWallet.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_NoWallet.buttonText`,
    `${PageName.Metamask}_Connecting.statusText`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart3`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart4`,
    `${PageName.Metamask}_Error.statusText`,
    `${PageName.Metamask}_Error.descriptionText`,
    `${PageName.Metamask}_Error.buttonText`,
    `${PageName.Metamask}_Sign.statusText`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart3`,
    `${PageName.Metamask}_Connected.statusText`,
    `${PageName.Metamask}_Connected.descriptionText`,
  ],
  AUTH: [
    `${PageName.Auth}.title`,
    `${PageName.Auth}.socialsTitle`,
    `${PageName.Auth}.walletTitle`,
    `${PageName.Auth}.twitter`,
    `${PageName.Auth}.google`,
    `${PageName.Auth}.email`,
    `${PageName.Auth}.metamask`,
  ],
  HELLO: [
    `${PageName.Hello}.mascotTextHighlightedPart1`,
    `${PageName.Hello}.mascotTextHighlightedPart2`,
    `${PageName.Hello}.answerButtonText`,
  ],
  MAIL_AUTHORIZATION: [
    `${PageName.MailAuthorization}.mailLabel`,
    `${PageName.MailAuthorization}.mailErrorText_pattern`,
    `${PageName.MailAuthorization}.mailPlaceholder`,
    `${PageName.MailAuthorization}.passwordLabel`,
    `${PageName.MailAuthorization}.passwordErrorText_minLength`,
    `${PageName.MailAuthorization}.passwordPlaceholder`,
    `${PageName.MailAuthorization}.button`,
  ],
  HEADER: [`${PageName.Header}.buttonLogin`],
};
