import { ErrorType } from './Errors';
import { PageName } from './PageNames';

export const VOICE_KEYS = {
  GUIDES_GALLERY: [`${PageName.GuidesGallery}.mascotVioce`],
  HELLO: [`${PageName.Hello}.mascotVioce`],
  PROFILE_GUIDES: [`${PageName.ProfileGuides}.mascotVioce`],
  PROFILE_REFERALS: [
    `${PageName.ProfileReferals}_Refferal.mascotVioce`,
    `${PageName.ProfileReferals}_NoRefferal.mascotVioce`,
  ],
  METAMASK_CONNECT: [
    `${PageName.Metamask}_NoWallet.statusText`,
    `${PageName.Metamask}_NoWallet.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_NoWallet.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_NoWallet.buttonText`,
    `${PageName.Metamask}_Connecting.statusText`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart3`,
    `${PageName.Metamask}_Connecting.descriptionTextHighlightedPart4`,
    `${PageName.Metamask}_Error.statusText`,
    `${PageName.Metamask}_Error.descriptionText`,
    `${PageName.Metamask}_Error.buttonText`,
    `${PageName.Metamask}_Sign.statusText`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart1`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart2`,
    `${PageName.Metamask}_Sign.descriptionTextHighlightedPart3`,
    `${PageName.Metamask}_Connected.statusText`,
    `${PageName.Metamask}_Connected.descriptionText`,
  ],
  PROFILE_SETTINGS: [
    `${PageName.ProfileSettings}.userNameTitle`,
    `${PageName.ProfileSettings}.socialTitle`,
    `${PageName.ProfileSettings}.connectMail`,
    `${PageName.ProfileSettings}.connectTwitter`,
    `${PageName.ProfileSettings}.setPass`,
    `${PageName.ProfileSettings}.logout`,
    `${PageName.ProfileSettings}.editMailTitle`,
    `${PageName.ProfileSettings}.editNameTitle`,
    `${PageName.ProfileSettings}.setPassTitle`,
    `${PageName.ProfileSettings}.changePassTitle`,
    `${PageName.ProfileSettings}.fieldName`,
    `${PageName.ProfileSettings}.fieldMail`,
    `${PageName.ProfileSettings}.fieldPass`,
    `${PageName.ProfileSettings}.fieldEnterPass`,
    `${PageName.ProfileSettings}.fieldRepeatPass`,
    `${PageName.ProfileSettings}.fieldLastPass`,
    `${PageName.ProfileSettings}.fieldNewPass`,
    `${PageName.ProfileSettings}.connectSocial`,
    `${PageName.ProfileSettings}.socialGoogle`,
    `${PageName.ProfileSettings}.btnSave`,
  ],
  PROFILE_WALLET: [
    `${PageName.ProfileWallet}.formTitle`,
    `${PageName.ProfileWallet}.statusWallet`,
    `${PageName.ProfileWallet}.balanceTitle`,
    `${PageName.ProfileWallet}.balanceValue`,
    `${PageName.ProfileWallet}.networkTitle`,
    `${PageName.ProfileWallet}.networkName`,
    `${PageName.ProfileWallet}.statusForm`,
  ],
};
